---
- name: Install ArgoCD on Kubernetes Clusters
  hosts: localhost
  become: yes
  vars:
    argocd_namespace: argocd
    ingress_host: "argocd.sysadmin.homes"

  tasks:
    - name: Add ArgoCD repository for Helm
      ansible.builtin.command: helm repo add argo https://argoproj.github.io/argo-helm
      ignore_errors: yes

    - name: Update Helm repository
      ansible.builtin.command: helm repo update
      ignore_errors: yes

    - name: Install ArgoCD using Helm
      ansible.builtin.command: helm install -n {{ argocd_namespace }} argocd argo/argo-cd
      ignore_errors: yes

    - name: Pause to allow ArgoCD to initialize
      pause:
        minutes: 2

    - name: Configure ingress for ArgoCD
      ansible.builtin.shell: |
        kubectl apply -f <<EOF
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: argocd-ingress
          namespace: {{ argocd_namespace }}
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        spec:
          ingressClassName: nginx
          rules:
            - host: {{ ingress_host }}
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: argocd-server
                        port:
                          number: 443
        EOF
      ignore_errors: yes

    - name: 