apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: finance-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: finance-app
  minReplicas: 3
  maxReplicas: 7
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 512Mi
  - type: Pods
    pods:
      metric:
        name: packets_per_second
      target:
        type: AverageValue
        averageValue: 100