apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/ebs.csi.aws.com
  name: pv-demo
  uid: d52af557-edf5-4f96-8e89-42a3008209e6
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-demo
    namespace: default
    uid: c9a44c07-cffa-4cd8-b92b-15bac9a9b984
  csi:
    driver: ebs.csi.aws.com
    csi.storage.k8s.io/fstype: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: "12345678901234567890-12345678901234567890-aws-ebs-csi-driver"
    volumeHandle: vol-0a1b2c3d4e5f67890  # Replace with your actual EBS volume ID
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-west-2a  # Replace with the correct availability zone
  persistentVolumeReclaimPolicy: Retain  # Can be Delete based on your use case
  storageClassName: ebs-sc
  volumeMode: Filesystem
status:
  phase: Bound
