---
- name: Configure Prometheus with Prometheus Operator
  hosts: kube_nodes
  tasks:
    - name: Create Prometheus ConfigMap
      kubernetes.core.k8s:
        state: present
        namespace: monitoring
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: prometheus-config
            namespace: monitoring
          data:
            prometheus.yml: |
              global:
                scrape_interval: 15s
                evaluation_interval: 15s

              scrape_configs:
                - job_name: 'kubernetes-nodes'
                  kubernetes_sd_configs:
                    - role: node

                - job_name: 'kubernetes-pods'
                  kubernetes_sd_configs:
                    role: pod

                - job_name: 'chaos-exporter'
                  static_configs:
                    - targets: ['chaos-exporter.litmus.svc.cluster.local:8080']
                  relabel_configs:
                    - target_label: instance
                      replacement: 'chaos-exporter-service'

    - name: Create Prometheus Custom Resource (CR)
      kubernetes.core.k8s:
        state: present
        namespace: monitoring
        definition:
          apiVersion: monitoring.coreos.com/v1
          kind: Prometheus
          metadata:
            name: prometheus
            namespace: monitoring
          spec:
            replicas: 3
            serviceAccountName: prometheus
            serviceMonitorSelector: {}
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "200m"
            storage:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi

    - name: Create ServiceMonitor for Kubernetes Nodes
      kubernetes.core.k8s:
        state: present
        namespace: monitoring
        definition:
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: kubernetes-nodes
            namespace: monitoring
          spec:
            selector:
              matchLabels:
                k8s-app: prometheus
            endpoints:
              - port: http
                interval: 15s
                path: /metrics
                targetPort: 9100
            namespaceSelector:
              any: true

    - name: Create ServiceMonitor for Kubernetes Pods
      kubernetes.core.k8s:
        state: present
        namespace: monitoring
        definition:
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: kubernetes-pods
            namespace: monitoring
          spec:
            selector:
              matchLabels:
                k8s-app: prometheus
            endpoints:
              - port: http
                interval: 15s
                path: /metrics
                targetPort: 8080
            namespaceSelector:
              any: true

    - name: Configure Prometheus Alertmanager (Optional)
      kubernetes.core.k8s:
        state: present
        namespace: monitoring
        definition:
          apiVersion: monitoring.coreos.com/v1
          kind: Alertmanager
          metadata:
            name: alertmanager
            namespace: monitoring
          spec:
            replicas: 3
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "200m"
