- name: Install and Configure Velero on Azure with File System Backup
  hosts: localhost
  become: yes
  vars:
    velero_version: v1.15.0
    velero_namespace: velero
    azure_container: "your-azure-container-name"
    resource_group: "your-resource-group"
    storage_account: "your-storage-account"
  tasks:
    - name: Ensure Velero namespace exists
      kubernetes.core.k8s:
        state: present
        kind: Namespace
        name: "{{ velero_namespace }}"

    - name: Create Azure credentials secret for Velero
      kubernetes.core.k8s:
        state: present
        namespace: "{{ velero_namespace }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloud-credentials
          data:
            cloud: "{{ lookup('file', 'azure-credentials.txt') | b64encode }}"

    - name: Download Velero binary from GitHub
      get_url:
        url: "https://github.com/vmware-tanzu/velero/releases/download/{{ velero_version }}/velero-{{ velero_version }}-linux-amd64.tar.gz"
        dest: "/tmp/velero-{{ velero_version }}-linux-amd64.tar.gz"
        mode: '0755'

    - name: Extract Velero tarball
      unarchive:
        src: "/tmp/velero-{{ velero_version }}-linux-amd64.tar.gz"
        dest: "/tmp/velero-{{ velero_version }}"
        remote_src: yes

    - name: Move Velero binary to /usr/local/bin
      copy:
        src: "/tmp/velero-{{ velero_version }}/velero"
        dest: /usr/local/bin/velero
        mode: '0755'

    - name: Install Velero on Azure with File System Backup (FSB) and Node Agent
      command: >
        velero install --provider azure
        --bucket "{{ azure_container }}"
        --secret-file azure-credentials.txt
        --backup-location-config resourceGroup="{{ resource_group }}",storageAccount="{{ storage_account }}"
        --namespace "{{ velero_namespace }}"
        --plugins velero/velero-plugin-for-microsoft-azure
        --use-node-agent
        --privileged-node-agent
        --default-volumes-to-fs-backup
        --features=EnableCSI

    - name: Validate Velero installation
      command: kubectl get pods -n "{{ velero_namespace }}"
      register: velero_pods
      until: velero_pods.stdout.find('Running') != -1
      retries: 5
      delay: 15
      ignore_errors: yes