variable "resource_group_name" {}
variable "location" {}
variable "vnet_name" {}
variable "subnet_name" {}
variable "nsg_name" {}
variable "nic_name" {}
variable "public_ip_name" {}
variable "vm_name" {}
variable "vm_size" {}
variable "admin_username" {}
variable "jenkins_server_tag" {}
